on:
  workflow_dispatch:

env:
  RELEASE_NAME: SteamShortcut
  DOTNET_VERSION: '9.0.x'

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Install dependencies
        run: dotnet restore
      - name: Set initial RELEASE_VERSION
        shell: bash
        run: |
          majorMinor=$(cat VERSION | tr -d '[:space:]')

          if [ -z "$(git tag --list)" ]; then
            nextVer="${majorMinor}.1"
          else
            lastVer=$(git tag --sort=-v:refname --list "${majorMinor}.*" | head -n1)
            if [ -z "$lastVer" ]; then
              nextVer="${majorMinor}.1"
            else
              IFS='.' read -ra parts <<< "$lastVer"
              nextPatch=$((parts[2] + 1))
              nextVer="${parts[0]}.${parts[1]}.$nextPatch"
            fi
          fi

          echo "RELEASE_VERSION=$nextVer" >> $GITHUB_ENV
          echo "Using version: \"$nextVer\""
      - name: Validate variables
        shell: bash
        run: |
          echo "RELEASE_VERSION: ${{ env.RELEASE_VERSION }}"
          echo "RELEASE_NAME: ${{ env.RELEASE_NAME }}"
          if [ -z "${{ env.RELEASE_VERSION }}" ]; then
            echo "::error::RELEASE_VERSION is empty"
            exit 1
          fi
      - name: Normalize version
        shell: bash
        run: |
          clean_version=$(echo "${{ env.RELEASE_VERSION }}" | tr -d '[:space:]')
          echo "RELEASE_VERSION=${clean_version}" >> $GITHUB_ENV
      - name: Build Release
        shell: pwsh
        run: |
          $version = "${{ env.RELEASE_VERSION }}"
          dotnet publish SteamShortcut/SteamShortcut.csproj -p:PublishSingleFile=true --self-contained false --output "${{ env.RELEASE_NAME }}-$version/" "/p:AssemblyVersion=$version" "/p:Version=$version" "/p:VersionSuffix=" "/p:ExtraDefineConstants=PRODUCTION_BUILD" -p:DebugType=None -p:DebugSymbols=false
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - uses: vimtor/action-zip@v1
        with:
          files: ${{ env.RELEASE_NAME }}-${{ env.RELEASE_VERSION }}
          dest: ${{ env.RELEASE_NAME }}-${{ env.RELEASE_VERSION }}-portable.zip
          recursive: true
      - name: Update version in RELEASE.md
        shell: bash
        run: |
          sed -i 's|#{GIT_TAG_NAME}|${{ env.RELEASE_VERSION }}|g' RELEASE.md
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}
          artifacts: "*.zip"
          prerelease: true
          generateReleaseNotes: true
          bodyFile: RELEASE.md
